version: 2
jobs:
  build:
    working_directory: ~/tokenstudio
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://circleci:circleci@127.0.0.1:5432/circleci
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
          POSTGRES_PASSWORD: circleci
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ .Branch }}
            - gem-cache

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache

      - run: yarn install

      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load db:seed --trace

      - run:
          command: bundle exec rails test
          when: always

      - store_test_results:
          path: test/

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
